# Generated by Django 5.2.1 on 2025-05-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_playlistsong_options_and_more'),
        ('users', '0002_playhistory_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_playlists',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='playlist.playlist'),
        ),
        migrations.DeleteModel(
            name='PlayHistory',
        ),
    ]
