# Generated by Django 5.2.1 on 2025-05-28 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('playlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
