# Generated by Django 5.2.1 on 2025-05-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_playlistsong_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='playlist.hashtag'),
        ),
    ]
