# Generated by Django 5.2.1 on 2025-05-28 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_hashtag_playlist_hashtags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='users',
            field=models.ManyToManyField(related_name='hashtag_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
