# Generated by Django 5.2.1 on 2025-05-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_hashtag_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playhistory',
            name='song',
        ),
        migrations.RemoveField(
            model_name='playhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='PlayHistory',
        ),
    ]
