# Generated by Django 5.2.1 on 2025-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_remove_playhistory_song_remove_playhistory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='playlist.hashtag'),
        ),
    ]
