# Generated by Django 5.2.1 on 2025-06-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_album_delete_album'),
        ('playlist', '0006_alter_playlist_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', through='playlist.PlaylistSong', to='music.song'),
        ),
    ]
