# Generated by Django 5.2.1 on 2025-06-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_genre_remove_song_created_at_and_more'),
        ('playlist', '0007_playlist_songs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('playlist', 'song')},
        ),
    ]
